// 部署到 Cloudflare Workers 控制台或 wrangler CLI
export default {
  async fetch(request, env) {
    try {
      const { searchParams } = new URL(request.url);
      const subUrl = searchParams.get("url");
      const target = searchParams.get("target") || "clash";

      if (!subUrl) {
        return new Response("Missing url parameter", { status: 400 });
      }

      const res = await fetch(subUrl);
      if (!res.ok) throw new Error("Fetch failed: " + res.status);
      const raw = await res.text();

      // 简单 YAML 构建
      const nodes = raw
        .split("\n")
        .filter(l => l.trim())
        .map((l, i) =>
          `  - name: "Node-${i + 1}"\n    type: external\n    remark: "${l.trim()}"`
        )
        .join("\n");

      const yaml = `# Generated by SubFusion\nproxies:\n${nodes}\n\nproxy-groups:\n  - name: 🚀 Proxy\n    type: select\n    proxies:\n${nodes
        .split("\n")
        .filter(l => l.includes("name:"))
        .map(l => "      - " + l.split('"')[1])
        .join("\n")}\n\nrules:\n  - MATCH,🚀 Proxy\n`;

      return new Response(yaml, {
        headers: {
          "Content-Type": "text/yaml; charset=utf-8",
          "Cache-Control": "no-cache",
        },
      });
    } catch (err) {
      return new Response("Error: " + err.message, { status: 500 });
    }
  },
};
